# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x65vent.proto\x12\x05proto\"K\n\x08\x42usEvent\x12\x0c\n\x04unit\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x1e\n\ncoordinate\x18\x03 \x01(\x0b\x32\n.proto.UTM\"(\n\x03UTM\x12\x0f\n\x07\x65\x61sting\x18\x01 \x01(\x01\x12\x10\n\x08northing\x18\x02 \x01(\x01\x62\x06proto3')
)




_BUSEVENT = _descriptor.Descriptor(
  name='BusEvent',
  full_name='proto.BusEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unit', full_name='proto.BusEvent.unit', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='proto.BusEvent.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='proto.BusEvent.coordinate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=97,
)


_UTM = _descriptor.Descriptor(
  name='UTM',
  full_name='proto.UTM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='easting', full_name='proto.UTM.easting', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='northing', full_name='proto.UTM.northing', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=139,
)

_BUSEVENT.fields_by_name['coordinate'].message_type = _UTM
DESCRIPTOR.message_types_by_name['BusEvent'] = _BUSEVENT
DESCRIPTOR.message_types_by_name['UTM'] = _UTM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BusEvent = _reflection.GeneratedProtocolMessageType('BusEvent', (_message.Message,), dict(
  DESCRIPTOR = _BUSEVENT,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:proto.BusEvent)
  ))
_sym_db.RegisterMessage(BusEvent)

UTM = _reflection.GeneratedProtocolMessageType('UTM', (_message.Message,), dict(
  DESCRIPTOR = _UTM,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:proto.UTM)
  ))
_sym_db.RegisterMessage(UTM)


# @@protoc_insertion_point(module_scope)
